In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv("../artifacts/raw_data/retail_store_inventory.csv")

In [3]:
df = pd.DataFrame(data)

In [4]:
df.head()

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Price,Discount,Weather Condition,Promotion,Competitor Pricing,Seasonality,Epidemic,Demand
0,2022-01-01,S001,P0001,Electronics,North,195,102,252,72.72,5,Snowy,0,85.73,Winter,0,115
1,2022-01-01,S001,P0002,Clothing,North,117,117,249,80.16,15,Snowy,1,92.02,Winter,0,229
2,2022-01-01,S001,P0003,Clothing,North,247,114,612,62.94,10,Snowy,1,60.08,Winter,0,157
3,2022-01-01,S001,P0004,Electronics,North,139,45,102,87.63,10,Snowy,0,85.19,Winter,0,52
4,2022-01-01,S001,P0005,Groceries,North,152,65,271,54.41,0,Snowy,0,51.63,Winter,0,59

In [6]:
df.shape

(76000, 16)

### 1. Understand the meaning of each columns

In [11]:
df.columns

Index(['Date', 'Store ID', 'Product ID', 'Category', 'Region',
       'Inventory Level', 'Units Sold', 'Units Ordered', 'Price', 'Discount',
       'Weather Condition', 'Promotion', 'Competitor Pricing', 'Seasonality',
       'Epidemic', 'Demand'],
      dtype='object')

### 2. Understand the different values in each column

In [12]:
for column in df.columns:
    print(f"\n{'='*60}")
    print(f"Column: {column}")
    print(f"Number of unique values: {df[column].nunique()}")
    print("\nValue counts:")
    print(df[column].value_counts())

============================================================
Column: Date
Number of unique values: 760

Value counts:
Date
2024-01-30    100
2022-01-01    100
2022-01-02    100
2022-01-03    100
2022-01-04    100
             ...
2022-01-13    100
2022-01-12    100
2022-01-11    100
2022-01-10    100
2022-01-09    100
Name: count, Length: 760, dtype: int64

============================================================
Column: Store ID
Number of unique values: 5

Value counts:
Store ID
S001    15200
S002    15200
S003    15200
S004    15200
S005    15200
Name: count, dtype: int64

============================================================
Column: Product ID
Number of unique values: 20

Value counts:
Product ID
P0001    3800
P0002    3800
P0003    3800
P0004    3800
P0005    3800
P0006    3800
P0007    3800
P0008    3800
P0009    3800
P0010    3800
P0011    3800
P0012    3800
P0013    3800
P0014    3800
P0015    3800
P0016    3800
P0017    3800
P0018    3800
P0019    3800
P0020    3800
Name: count, dtype: int64

============================================================
Column: Category
Number of unique values: 5

Value counts:
Category
Groceries      30400
Furniture      13680
Clothing       12160
Toys           10640
Electronics     9120
Name: count, dtype: int64

============================================================
Column: Region
Number of unique values: 4

Value counts:
Region
North    30400
South    15200
East     15200
West     15200
Name: count, dtype: int64

============================================================
Column: Inventory Level
Number of unique values: 1426

Value counts:
Inventory Level
0       406
119     315
123     310
135     309
127     303
       ...
1644      1
1571      1
1172      1
1488      1
1037      1
Name: count, Length: 1426, dtype: int64

============================================================
Column: Units Sold
Number of unique values: 330

Value counts:
Units Sold
72     790
80     782
79     776
74     769
68     765
      ...
307      1
313      1
314      1
319      1
336      1
Name: count, Length: 330, dtype: int64

============================================================
Column: Units Ordered
Number of unique values: 996

Value counts:
Units Ordered
0       47107
50       1047
101       181
97        180
107       173
        ...
1068        1
876         1
1086        1
1134        1
946         1
Name: count, Length: 996, dtype: int64

============================================================
Column: Price
Number of unique values: 15396

Value counts:
Price
23.34     22
22.31     21
20.97     20
23.67     20
20.78     20
          ..
170.78     1
164.78     1
159.48     1
114.87     1
156.34     1
Name: count, Length: 15396, dtype: int64

============================================================
Column: Discount
Number of unique values: 6

Value counts:
Discount
10    23298
0     17126
5     16918
15     6245
25     6222
20     6191
Name: count, dtype: int64

============================================================
Column: Weather Condition
Number of unique values: 4

Value counts:
Weather Condition
Cloudy    24360
Sunny     22980
Rainy     17500
Snowy     11160
Name: count, dtype: int64

============================================================
Column: Promotion
Number of unique values: 2

Value counts:
Promotion
0    51000
1    25000
Name: count, dtype: int64

============================================================
Column: Competitor Pricing
Number of unique values: 15963

Value counts:
Competitor Pricing
27.02     22
24.58     21
25.85     20
24.94     20
25.45     19
          ..
158.27     1
5.82       1
154.92     1
131.52     1
140.13     1
Name: count, Length: 15963, dtype: int64

============================================================
Column: Seasonality
Number of unique values: 4

Value counts:
Seasonality
Winter    21000
Spring    18400
Summer    18400
Autumn    18200
Name: count, dtype: int64

============================================================
Column: Epidemic
Number of unique values: 2

Value counts:
Epidemic
0    60800
1    15200
Name: count, dtype: int64

============================================================
Column: Demand
Number of unique values: 340

Value counts:
Demand
88     743
102    732
100    723
103    722
90     704
      ...
296      1
286      1
325      1
331      1
370      1
Name: count, Length: 340, dtype: int64

In [10]:
df.head()

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Price,Discount,Weather Condition,Promotion,Competitor Pricing,Seasonality,Epidemic,Demand
0,2022-01-01,S001,P0001,Electronics,North,195,102,252,72.72,5,Snowy,0,85.73,Winter,0,115
1,2022-01-01,S001,P0002,Clothing,North,117,117,249,80.16,15,Snowy,1,92.02,Winter,0,229
2,2022-01-01,S001,P0003,Clothing,North,247,114,612,62.94,10,Snowy,1,60.08,Winter,0,157
3,2022-01-01,S001,P0004,Electronics,North,139,45,102,87.63,10,Snowy,0,85.19,Winter,0,52
4,2022-01-01,S001,P0005,Groceries,North,152,65,271,54.41,0,Snowy,0,51.63,Winter,0,59

### 3. Check Data Types

In [13]:
df.dtypes

Date                   object
Store ID               object
Product ID             object
Category               object
Region                 object
Inventory Level         int64
Units Sold              int64
Units Ordered           int64
Price                 float64
Discount                int64
Weather Condition      object
Promotion               int64
Competitor Pricing    float64
Seasonality            object
Epidemic                int64
Demand                  int64
dtype: object

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76000 entries, 0 to 75999
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Date                76000 non-null  object
 1   Store ID            76000 non-null  object
 2   Product ID          76000 non-null  object
 3   Category            76000 non-null  object
 4   Region              76000 non-null  object
 5   Inventory Level     76000 non-null  int64
 6   Units Sold          76000 non-null  int64
 7   Units Ordered       76000 non-null  int64
 8   Price               76000 non-null  float64
 9   Discount            76000 non-null  int64
 10  Weather Condition   76000 non-null  object
 11  Promotion           76000 non-null  int64
 12  Competitor Pricing  76000 non-null  float64
 13  Seasonality         76000 non-null  object
 14  Epidemic            76000 non-null  int64
 15  Demand              76000 non-null  int64
dtypes: float64(2), int64(7), object(7)
memory usage: 9.3+ MB

### 4. Check Missing values in a column

In [16]:
df.isnull().sum()

Date                  0
Store ID              0
Product ID            0
Category              0
Region                0
Inventory Level       0
Units Sold            0
Units Ordered         0
Price                 0
Discount              0
Weather Condition     0
Promotion             0
Competitor Pricing    0
Seasonality           0
Epidemic              0
Demand                0
dtype: int64

### 5. Check for duplicates

In [17]:
df.duplicated().sum()

np.int64(0)

### 6. Quickly understanding our numerical data.

In [18]:
df.describe()

,Inventory Level,Units Sold,Units Ordered,Price,Discount,Promotion,Competitor Pricing,Epidemic,Demand
count,76000.000000,76000.000000,76000.000000,76000.000000,76000.000000,76000.000000,76000.000000,76000.000000,76000.000000
mean,301.062842,88.827316,89.090645,67.726028,9.087039,0.328947,69.454029,0.200000,104.317158
std,226.510161,43.994525,162.404627,39.377899,7.475781,0.469834,40.943818,0.400003,46.964801
min,0.000000,0.000000,0.000000,4.740000,0.000000,0.000000,4.290000,0.000000,4.000000
25%,136.000000,58.000000,0.000000,31.997500,5.000000,0.000000,32.620000,0.000000,71.000000
50%,227.000000,84.000000,0.000000,64.500000,10.000000,0.000000,65.700000,0.000000,100.000000
75%,408.000000,114.000000,121.000000,95.830000,10.000000,1.000000,97.932500,0.000000,133.000000
max,2267.000000,426.000000,1616.000000,228.030000,25.000000,1.000000,261.220000,1.000000,430.000000